apiVersion: apps/v1
kind: Deployment
metadata:
  name: watson-nlp-runtime
spec:
  selector:
    matchLabels:
      app: watson-nlp-runtime
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: watson-nlp-runtime
    spec:
      initContainers:
      - name: emotion-aggregated-workflow-lang-en-stock
        image: cp.icr.io/cp/ai/watson-nlp_emotion_aggregated-workflow_lang_en_stock:1.0.9
        volumeMounts:
        - name: model-directory
          mountPath: "/app/models"
        env:
        - name: ACCEPT_LICENSE
          value: 'true'
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
      containers:
      - name: watson-nlp-runtime
        image: cp.icr.io/cp/ai/watson-nlp-runtime:1.1.0
        env:
        - name: ACCEPT_LICENSE
          value: 'true'
        - name: LOCAL_MODELS_DIR
          value: "/app/models"
        - name: LOG_LEVEL
          value: debug
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
            ephemeral-storage: "2Gi"
          limits:
            memory: "6Gi"
            cpu: "3"
            ephemeral-storage: "2Gi"
        ports:
        - containerPort: 8080
        - containerPort: 8085
        livenessProbe:
          httpGet:
            path: /swagger/
            port: 8080
          initialDelaySeconds: 150
        volumeMounts:
        - name: model-directory
          mountPath: "/app/models"
      volumes:
      - name: model-directory
        emptyDir:
          sizeLimit: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: watson-nlp-runtime-service
spec:
  type: ClusterIP
  selector:
    app: watson-nlp-runtime
  ports:
  - port: 8080
    name: http-rest-svc
    protocol: TCP
    targetPort: 8080
  - port: 8085
    name: http-grpc-svc
    protocol: TCP
    targetPort: 8085
  
